#!/usr/bin/env bash
# install nginx, 404 not found
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error = "error_page 404 /404.html;\n\location = /404.html {\nroot /var/www/html;\ninternal;\n}"
line="location /redirect_me {rewrite ^/(.*)$ http://www.youtube.com permanent;}"
location="/etc/nginx/sites-enabled/default"
sudo sed -i "36i $line" "$location"
sudo sed -i "25i $error" "$location"
sudo service nginx restart
