#!/usr/bin/env bash
# Will display Holberton School and Hi using while and if

i=0 

while [ $i -lt 10 ]

do 
        echo "Holberton School"
       
	if [ "$i" -eq '9' ] 
	then  
        	echo "hi"
    fi
   i=$(( i+1 ))
done
