#!/usr/bin/env bash
# This will loop 1 to 10 and print out bad luck on 4 and good luck on 8

i=1 

while [ $i -lt 10 ]

do 
	if 
        [ "$i" -eq "4" ]
	then    
        	echo "bad luck"
        
elif    [[ "$i" -eq "8" ]] 
then    
        echo "good luck"

	else 
		echo "Holberton School"
fi 
        i=$((i+1))
done
